### ISSUE TITLE
What tools did you use to build the environments?

### ISSUE THREAD

**Issue by GoingMyWay** [MicroSTM/AGENT-synthesis#1]
Hi, I am curious did you use Unity3D to create the environments in this repo?

**Comment by MicroSTM** [comment]
We were using ThreeDWorld (https://threedworld.org/) which was built on Unity.

**Comment by GoingMyWay** [comment]
> We were using ThreeDWorld (https://threedworld.org/) which was built on Unity.

That's awesome.
